name: Build and Deploy Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

env:
  NODE_VERSION: "18.x"
  # Assuming your build output is the 'dist' directory.
  # If it's a static site with no build, change this to '.'
  BUILD_DIR: 'dist'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies
        if: steps.check_files.outputs.has_package_json == 'true'
        run: |
          npm ci

      - name: Create .env File
        if: steps.check_files.outputs.has_package_json == 'true'
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env

      - name: Build Project
        if: steps.check_files.outputs.has_package_json == 'true'
        run: |
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: ${{ env.BUILD_DIR }}
          if-no-files-found: error # Fails if the build directory is empty

  deploy:
    name: Deploy to Firebase & GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Deploy only on pushes to main

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: ${{ env.BUILD_DIR }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.BUILD_DIR }}
          branch: gh-pages
          clean: true

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: newfat2fitauth

      - name: Deployment Summary
        run: |
          echo "✅ Deployment Complete!"
          echo "🌐 Live Site: https://www.fat2fitxpress.com"
          echo "📊 GitHub Pages: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://www.fat2fitxpress.com
            https://www.fat2fitxpress.com/blog.html
          uploadArtifacts: true
          temporaryPublicStorage: true
